on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple # this will create a PR with an updated CHANGELOG.md and a new release
